# Generated by Django 4.2.5 on 2023-09-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtors',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
